[package]
name = "pager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
doubly-linked-list = "0.2.0"
log = "0.4.17"
preprint = "0.1"


[features]
default = ["buddy"]
bitmap = []
buddy = []


[dev-dependencies]
env_logger = "0.10.0"
pager = { path = "../pager", features = ["bitmap", "buddy"] }
rand = "0.8.4"